version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./app.dockerfile
    container_name: im_web
    ports:
      - "5173:80"
    restart: always
    networks:
      - im_net
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_WEBSOCKET: ${VITE_WEBSOCKET}
      VITE_LIVEKIT: ${VITE_LIVEKIT}

networks:
  im_net:
    external: true