version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./APP.dockerfile
    container_name: im_web
    ports:
      - "5000:80"
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: "http://127.0.0.1:8080"
      REACT_APP_WEBSOCKET: "ws://127.0.0.1:8080"
      REACT_APP_LIVEKIT: "http://127.0.0.1:7880"
